### ISSUE TITLE
Error trying to find a log in mongo. 

### ISSUE THREAD

**Issue by Ruckingfetarded** [Ronak0020/discord-utility#1]
` let data = await schema.findOne(options).catch(e => {`
`TypeError: Cannot read property 'findOne' of undefined`

So I am trying to use Discord-Util to create per-server-settings. I am creating it so when my bot joins a server it checks if there's any data for that server and if there isn't then it will create data. I am getting this error while trying to find that data, I have already made it connect to mongoDB using the `DiscordUtil.mongoConnect()` function and I just end up still getting that error.

**Comment by Ronak0020** [comment]
Can you provide the code where you have defined your `schema`?

**Comment by Ronak0020** [comment]
## Issue has been solved in DMs. Wasn't and issue with package
